services:
  - type: web
    name: fam-bottling-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: TIMELESS_EMAIL
        value: timelessbyemjay@gmail.com
